name: Annie Lynne // Design
favicon: null
layout_spectrum: 0.6983509939163923
typography_spectrum: 0.3063707200344652
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.970508111640811
  lightness: 0.28512167651206255
  saturation: 0.8088449710048735
  rhythmicContrast: 0.4256097599864006
purpose: []
